# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cape < Formula
  desc ""
  homepage ""
  version "0.5.5"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/capeprivacy/cli/releases/download/v0.5.5/cape_Darwin_arm64.tar.gz"
      sha256 "fc5b820a30ff6b0fc3fefd7902862cec00928ee4d122b06640ae2d5844bd5c72"

      def install
        bin.install "cape"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/capeprivacy/cli/releases/download/v0.5.5/cape_Darwin_x86_64.tar.gz"
      sha256 "3d3f665e2fd040c1d9bca6f3cdcaa0198b60e096cd5739905b03f5fe72a26a77"

      def install
        bin.install "cape"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/capeprivacy/cli/releases/download/v0.5.5/cape_Linux_arm64.tar.gz"
      sha256 "613776390c75a824578027e0a382edd1a71f6a7934888730379cd91a55fc6467"

      def install
        bin.install "cape"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/capeprivacy/cli/releases/download/v0.5.5/cape_Linux_x86_64.tar.gz"
      sha256 "57a2bc4e55f725963faf9c881bcfd4d268d11499a42fdffcd84f59c698bdd6e2"

      def install
        bin.install "cape"
      end
    end
  end
end
